-- CREATE THE USER 
CREATE USER TASK6STAR
IDENTIFIED BY "OLAP"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
-- GRANT/REVOKE ROLE PRIVILEGES 
GRANT CONNECT TO TASK6STAR;
GRANT RESOURCE TO TASK6STAR;
-- GRANT/REVOKE SYSTEM PRIVILEGES 
GRANT UNLIMITED TABLESPACE TO TASK6STAR;

CREATE USER TASK6SNOWFLAKE
IDENTIFIED BY "OLAP"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
-- GRANT/REVOKE ROLE PRIVILEGES 
GRANT CONNECT TO TASK6SNOWFLAKE;
GRANT RESOURCE TO TASK6SNOWFLAKE;
-- GRANT/REVOKE SYSTEM PRIVILEGES 
GRANT UNLIMITED TABLESPACE TO TASK6SNOWFLAKE;