SELECT 
    P.NAME PRODUCT,
    F.QUANTITYFACT,
    F.DISCOUNTFACT,
    P.PRICE PRODUCTPRICE,
    P.PRICE * F.QUANTITYFACT * (100 - F.DISCOUNTFACT) / 100 ALLPRICE
FROM FACTS F, PRODUCTS P
    WHERE F.PRODUCTID = P.PRODUCTID
    AND P.PRICE > 400;
        
SELECT DISTINCT
    C.NAME,
    C.SURNAME,
    SUM(P.PRICE * F.QUANTITYFACT * (100 - F.DISCOUNTFACT) / 100) OVER(PARTITION BY C.CUSTOMERID) CUSTOMERPRICE 
FROM FACTS F, PRODUCTS P, CUSTOMERS C
    WHERE F.PRODUCTID = P.PRODUCTID
        AND F.CUSTOMERID = C.CUSTOMERID;